# Generated by Django 5.2.6 on 2025-11-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Curso')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo do Curso')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('grau_dificuldade', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20, verbose_name='Grau de Dificuldade')),
                ('resumo', models.TextField(verbose_name='Resumo do Curso')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Imagem do Curso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Curso Ativo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Aula')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Aula')),
                ('descricao', models.TextField(verbose_name='Descrição da Aula')),
                ('video', models.FileField(blank=True, help_text='Upload do arquivo de vídeo da aula', null=True, upload_to='courses/videos/', verbose_name='Vídeo da Aula')),
                ('duracao_minutos', models.PositiveIntegerField(default=0, help_text='Duração estimada da aula em minutos', verbose_name='Duração em Minutos')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição da aula na seção', verbose_name='Ordem da Aula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['section', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Arquivo')),
                ('arquivo', models.FileField(upload_to='courses/attachments/', verbose_name='Arquivo')),
                ('tipo_arquivo', models.CharField(blank=True, help_text='Ex: PDF, DOC, etc.', max_length=50, verbose_name='Tipo de Arquivo')),
                ('tamanho_kb', models.PositiveIntegerField(default=0, verbose_name='Tamanho do Arquivo (KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Anexo da Aula',
                'verbose_name_plural': 'Anexos das Aulas',
                'ordering': ['lesson', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Seção')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo da Seção')),
                ('descricao', models.TextField(verbose_name='Descrição da Seção')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição da seção no curso', verbose_name='Ordem da Seção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['course', 'ordem'],
                'unique_together': {('course', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section', verbose_name='Seção'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'ordem')},
        ),
    ]
