# Generated by Django 5.2.6 on 2025-11-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='descricao_subtitulo',
            field=models.TextField(blank=True, verbose_name='Descrição do Subtítulo'),
        ),
    ]
