# Generated by Django 5.2.8 on 2025-11-07 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_descricao_subtitulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.PositiveIntegerField(default=0, help_text='Posição atual do vídeo em segundos', verbose_name='Tempo Atual (segundos)')),
                ('completed', models.BooleanField(default=False, verbose_name='Aula Concluída')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='Última Visualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson', verbose_name='Aula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso da Aula',
                'verbose_name_plural': 'Progressos das Aulas',
                'ordering': ['-last_watched'],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
