# Generated by Django 5.2.8 on 2025-11-07 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão')),
                ('certificate_code', models.CharField(help_text='Código único para validação do certificado', max_length=50, unique=True, verbose_name='Código do Certificado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conclusão de Curso',
                'verbose_name_plural': 'Conclusões de Cursos',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
